23 02 07
euion/prac-clean-hikers pull request #2
Opened 2023-02-07 09:17 UTC by euion

## What is this PR? 📃
- 프로젝트명 : clean-hikers
- 요청 사항 : 라우팅 및 폴더 구조 피드백 주신거 반영했습니다. 해당 사항에 관하여 확인 부탁드려요
- 디자인(피그마 주소) : https://www.figma.com/file/oio4S2lJNO3hMhMSmRu8QG/%EC%97%98%EB%A6%AC%EC%8A%A4-AI%ED%8A%B8%EB%9E%99-5%EA%B8%B0-2%EC%B0%A8-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-10%ED%8C%80-(Copy)?t=EMEMeCTrPGLy3qum-1

<br />

## 작업내용 🔧
- 폴더구조 변경 (assets, components pages) 
- tailwindCSS 수정 및 반영 : navigation, main background-image, 폰트 
- 메인 화면 form 기능 수정중 : 현재 CSS만 구성.

<br />

## 스크린샷 📷

|기능|스크린샷|
|----|-------|
|이미지|![화면 캡처 2023-02-07 181323](https://user-images.githubusercontent.com/49273633/217201931-f307b692-41eb-423b-9c3b-3d4be89fdfdf.png)

**
<br />

## 테스트 체크리스트 🔧

- [ ]  tailwindCSS 반응형 확인 부탁드립니다.(navigation, background-image, form css)
- [ ] CSS 작업에 시간을 많이 쓴 상황이라 기능적인 부분보다 화면 구성을 위주로 확인 부탁 드립니다!

2023-02-07 09:35 UTC, AndrewKwon-kr requested changes
1.리뷰 사항들과 별개로 assets에 있는 파일들의 이름은 띄워쓰기 없이 작성하는 게 좋을 거 같아요
ex) Rectangle 1.svg -> Rectangle_1.svg

2.tailwindCSS 반응형 확인 부탁드립니다 << 이 부분 정확하게 이해를 못해서 코멘트를 못남겼습니다. 
https://tailwindcss.com/docs/responsive-design
제가 생각하는 반응형은 위와 같이 화면 너비에 따라 달라지는 것을 얘기하는 데, 확인해야될 부분이나 궁금한 점을 정확히 얘기해주시면 좋을 거 같아요!

2023-02-07 09:35 UTC, AndrewKwon-kr commented on src/common/nav/TheNavigation.vue
> +        <div class="w-2/5 items-center">
해당 부분은 max-width를 부여해서 큰 화면에서도 메뉴 간격을 일정하게 만드는 게 좀 더 보기 편할 거 같습니다

ex) 
![image](https://user-images.githubusercontent.com/85872325/217205528-5819d1fb-960d-427f-9616-d1fa96c0b22c.png)

2023-02-07 09:35 UTC, AndrewKwon-kr commented on src/main.js
> +app.use(Antd).mount('#app');
추 후에 글로벌로 적용할 라이브러리가 많아지게 되면 아래와 같은 형태가 좀 더 보기 편할 거 같습니다

```jsx
app.use(router);
app.use(Antd)

app.mount('#app');
```

2023-02-07 09:35 UTC, AndrewKwon-kr commented on src/pages/Main.vue
> +</style>
불필요한 부분은 지워주세요

2023-02-08 00:07 UTC, euion commented on src/common/nav/TheNavigation.vue
> +        <div class="w-2/5 items-center">
max-width 적용해서 일정하게 만들겠습니다

2023-02-08 00:07 UTC, euion commented on src/main.js
> +app.use(Antd).mount('#app');
반영하겠습니다 :)

2023-02-08 00:07 UTC, euion commented on src/pages/Main.vue
> +</style>
넵 반영하겠습니다 !

2023-02-08 00:23 UTC, euion commented on src/common/nav/TheNavigation.vue
> +        <div class="w-2/5 items-center">
수정완료하였습니다

2023-02-08 00:23 UTC, euion commented on src/main.js
> +app.use(Antd).mount('#app');
수정완료하였습니다

2023-02-08 00:23 UTC, euion commented on src/pages/Main.vue
> +</style>
수정완료하였습니다

2023-02-08 00:28 UTC, AndrewKwon-kr approved these changes

2023-02-08 00:29 UTC, merged