230208
euion/prac-clean-hikers pull request #3
Opened 2023-02-08 06:50 UTC by euion

## What is this PR? 📃
- 프로젝트명 : clean-hikers
- 요청 사항 : 메인 검색폼 props 전달 및 main의 navigation, footer의 반응형 CSS 확인 부탁드립니다.
- 디자인(피그마 주소) : https://www.figma.com/file/oio4S2lJNO3hMhMSmRu8QG/%EC%97%98%EB%A6%AC%EC%8A%A4-AI%ED%8A%B8%EB%9E%99-5%EA%B8%B0-2%EC%B0%A8-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-10%ED%8C%80-(Copy)?node-id=2%3A3&t=4frQF6sufjxMIZaq-1

<br />

## 작업내용 🔧
- Main 전체화면 max-width 적용
- 검색 바, navigation 바 반응형 배치 및 요소 간 상세 세부 배치 수정
-  페이지 별 컴포넌트 간 props 전달(Main -> MountainDetail)
- footer 링크 적용 및 세부 배치 작업

<br />

## 스크린샷 📷

|기능|스크린샷|
|----|-------|
|Main(메인) 페이지 : 지도, 데이터 부분 제외 구현 완료|![화면 캡처 2023-02-08 151026](https://user-images.githubusercontent.com/49273633/217453151-08ddfec8-0c2e-45d3-abc4-c6d8415d0837.png)|
|MountainDetail(산찾기) 페이지 :  props 전달 확인 완료 |![스크린샷_20230208_033845](https://user-images.githubusercontent.com/49273633/217453543-3a7a6897-2869-4f34-a061-7375d706e049.png)

<br />

## 테스트 체크리스트 🔧

- [ ] Main -> MountainDetail로 이동 시 검색 폼이 원활하게 작동하는지 확인 부탁 드립니다.
- [ ] navigation, footer의 CSS배치와 footer 관련 링크들이 잘 작동하는지 확인 부탁 드립니다.
- [ ] props 전달에 있어 의미 없거나 추가하지 않아도 될 코드들이 있는지 확인 부탁 드립니다. (관련 파일은 <b>Main.vue</b>(검색 폼 제출 페이지)-><b>MountainDetail.vue</b>(산 찾기 페이지)-><b>MountainName.vue</b>(테스트 상으로 넣어둔 페이지로부터 props 전달 받은 컴포넌트 ) 로 구성되어 있습니다.  )

2023-02-08 07:43 UTC, AndrewKwon-kr requested changes

2023-02-08 07:43 UTC, AndrewKwon-kr commented on src/components/SearchContainer.vue
> +            <option value="월악산">월악산</option>
option들을 배열로 묶어서 상태값으로 관리하고 v-for문으로 나타내보는건 어떨까요?

2023-02-08 07:43 UTC, AndrewKwon-kr commented on src/components/SearchContainer.vue
> +            <option value="6">6</option>
![image](https://user-images.githubusercontent.com/85872325/217459653-6b6acb95-d31b-4bd4-92d8-acb4818ca7fa.png)

해당 부분 참고해서 원래 의도대로 {{value}} 명으로 나타낼 수 있도록 해봅시다.

2023-02-08 07:43 UTC, AndrewKwon-kr commented on src/components/SearchContainer.vue
> +        <button
해당 버튼이 form에서 submit 역할을 하려했다면 버튼의 type을 submit으로 주어야 합니다.

https://ddol.tistory.com/56
위의 링크 참고해주세요.

2023-02-08 07:43 UTC, AndrewKwon-kr commented on src/components/SearchContainer.vue
> +        <button
그리고 현재 서버와 통신을 하고 있는 게 아니기 때문에 굳이 form을 쓰지 않아도 될 것 같아요.
이 부분은 굳이 수정하지는 않으셔도 됩니다.
https://7942yongdae.tistory.com/117

2023-02-08 07:43 UTC, AndrewKwon-kr commented on src/common/footer/MainFooter.vue
> +  <div class="bg-[#1D242B] py-9 px-16 flex justify-between">
![image](https://user-images.githubusercontent.com/85872325/217464678-2769852b-7712-441a-9bc1-bc6c4e5c88e4.png)
의도했던 화면구성을 정확히 모르겠으나, 위의 그림과 같은 좌우, 상하 방향의 스크롤바가 생긴건 홈 화면에선 부자연스러워 보입니다. 아래는 예시이지만, footer css를 수정할 필요는 있을 거 같아요
```jsx
<div
    class="bg-[#1D242B] py-9 px-16 flex justify-between absolute bottom-0 left-0 right-0"
  >
  ```

2023-02-08 07:43 UTC, AndrewKwon-kr commented on src/pages/MountainDetail.vue
> +  // props:{
꼭 필요한 것이 아닐 땐 pr 올리기 전에 주석은 정리해주시면 좋을 거 같아요

2023-02-08 12:12 UTC, euion commented on src/components/SearchContainer.vue
> +            <option value="월악산">월악산</option>
수정완료하였습니다!

2023-02-08 12:12 UTC, euion commented on src/components/SearchContainer.vue
> +            <option value="6">6</option>
수정완료하였습니다!

2023-02-08 12:13 UTC, euion commented on src/components/SearchContainer.vue
> +        <button
수정완료하였습니다!

2023-02-08 12:13 UTC, euion commented on src/common/footer/MainFooter.vue
> +  <div class="bg-[#1D242B] py-9 px-16 flex justify-between">
수정완료하였습니다!

2023-02-08 12:13 UTC, euion commented on src/pages/MountainDetail.vue
> +  // props:{
수정완료하였습니다!

2023-02-08 12:15 UTC, merged

2023-02-09 00:36 UTC, AndrewKwon-kr reviewed
수고하셨습니다